apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    namespace: default
    name: ingress-server-client
    annotations: {alb.ingress.kubernetes.io/scheme: internet-facing, alb.ingress.kubernetes.io/target-type: ip, alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]', alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}', alb.ingress.kubernetes.io/certificate-arn: 'arn:aws:acm:us-east-1:136717086005:certificate/dd4c5a93-909a-4def-b835-481b422a57fe', alb.ingress.kubernetes.io/actions.forward-multiple-tg: '{"type":"forward","forwardConfig":{"targetGroups":[{"serviceName":"kindredfinance-server-client-blue","servicePort":80,"weight":100},{"serviceName":"kindredfinance-server-client-green","servicePort":80,"weight":0}],"targetGroupStickinessConfig":{"enabled":true,"durationSeconds":100}}}'}
spec:
    ingressClassName: alb
    tls: [{hosts: [staging-aws.atom.finance]}]
    rules: [{http: {paths: [{path: /, pathType: Exact, backend: {service: {name: forward-multiple-tg, port: {name: use-annotation}}}}]}}]
